language: node_js
jobs:
  include:
  - stage: test
    script:
    - npm test
  - stage: release
    deploy:
      provider: script
      skip_cleanup: true
      script: npx semantic-release
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^(release|v)"
env:
  global:
    secure: RD0/XUULvq2LzjOO+2JaYSaUdj74MwEYjg2c3g+ANGI/diG1KjeP7j9qQraQtgZh5ike9uFq7iP0WRwKga4rhxDdxF42JOs1BupEDOIDh9oHjaAY8YuKjRfV/egLCGGuUIP3dEoK4ZKco0x9kkv/zj1ZTgj25kWQ032k68POrkMAPCEdLvxpdulb654rRCg0nDvU73yXYs/ItesT8BU5WPD2ZbbHZbiYXa4SVO7049p4bnq19pCtdWQ3N/p1CAnEZzQ1Aa2kHRe+ai3Ehqk3ydZ0CTMsi1E+xwvgEcEkRtsyyJ3KA14Es1dXJXyi4ajJO1LqnKGoA4gPoqSKwWeus8P02pNKgedAK3QY5219pVTFbt3tJWUFq2xsIHqxsfXDpJHN5UPIZl1u0TmMO+RLitTiBshKWFWyU9wX2pBZ2/DRR4iHv1/l7pXB0NLaf4swpg2MFug6m/Ymel0ZdN1zvS3dhRl/xpSDhI78YNR7N7LbCd3bk7D9z+QtE6zOxON2W/YAMHWM39rX8l3ltdpjJr4VVK99zP7IbdSRusoD3uVKH2+PF5gpU6W1pT69lxrC4c37wV/uvwCJulK9WE7q+8iCBfg3NbLVJCchHC1h7nq+Jbe+UaE6D8uWRYcnfT29WDu/8qvDFtsqW71gcq4BYlgAIh70muP1kdZUlu3SUoo=
