name: Continuous Integration

on:
  push:
    branches-ignore:
      - 'release'
  pull_request:
    branches:
      - '*'

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read .nvmrc
        id: nvmrc
        run: echo "::set-output name=node::$(cat .nvmrc)"

      - name: Use Node.js ${{ steps.nvmrc.outputs.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvmrc.outputs.node }}

      - name: Test
        run: |
          npm install
          npm test

      - name: Build
        run: npm run bundle
